name: Multiline example
on: push
jobs:
  terraform_main_job:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: |               ## since it is yaml we have used | and than multiline statement
          echo "Print some random message"
          ls -ltra
          cat README.md
