name: Example
on:
  push:
    branches:
      - main
      - '!feature/*'   # ignoring pushing to any branch name starting with feature using !
  pull_request:
    types:
      - opened
      - closed
    paths-ignore:   # Workflow will run when a PR is open or closed but exclude README.md file
      - README.md
    branches: 
      - main
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
    - run: echo This WF step is executed for event type - ${{ github.event_name}}
